
### Variables 
@apiurl = http://localhost:3333
@authToken = 



### Health Check
GET {{apiurl}}/health    

### Register User
POST {{apiurl}}/auth/register 
Content-Type: application/json

{
    "name": "sample",
    "email": "sample@sample.com",
    "password": "sample",
    "confirmPassword": "sample"
}

# @name login
### Login User
POST {{apiurl}}/auth/login 
Content-Type: application/json

{
    "email": "sample@sample.com",
    "password": "sample"
}

### Create Movie
POST {{apiurl}}/movies 
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "sample"
}

